### PR TITLE
Update metadata screenshot to an actual image of the browser

### PR DESCRIPTION
**Pull request by networkException**
Previously we would use a snap screenshot of vanilla chromium (which is a bit cursed)

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
Can you send this screenshot upstream? It's better to use screenshots that come directly from upstream.

**Comment by rany2** [comment]
Thank you!

**Comment by networkException** [comment]
> Can you send this screenshot to upstream? It's better to use screenshots that come directly from upstream.

what do you mean?

**Comment by rany2** [comment]
@networkException I think he wants you to host the screenshot in the main project (https://github.com/eloston/ungoogled-chromium) instead. So you could update the screenshot in one place and we would get the changes.

**Comment by networkException** [comment]
Ah sure we can do that

**Comment by TheEvilSkeleton** [comment]
> @networkException I think he wants you to host the screenshot in the main project (https://github.com/eloston/ungoogled-chromium) instead. So you could update the screenshot in one place and we would get the changes.

Just to confirm, yes, that's exactly what I want.

**Pull request merged**
